// FLASH.6.0 — previews operacionais. Nenhuma funcao grava ou envia.
var FLASH60 = (function () {
  var A={cartoes:'FIN_CARTOES',recargas:'FIN_CARTOES_RECARGAS',prestacoes:'FIN_CARTOES_LANCAMENTOS',extratos:'FIN_CARTOES_EXTRATOS',docs:'FIN_CARTOES_DOCUMENTOS / FIN_CARTOES_TERMOS',pendencias:'FIN_CARTOES_PENDENCIAS'},BRUNA='5553116198';
  function t(v){return String(v==null?'':v).trim();} function cpf(v){return t(v).replace(/\D/g,'');} function up(v){return t(v).toUpperCase();}
  function n(v){if(typeof v==='number')return isNaN(v)?0:v;var s=t(v).replace(/R\$/gi,'').replace(/\s/g,'');if(s.indexOf(',')>=0)s=s.replace(/\./g,'').replace(',','.');var x=Number(s);return isNaN(x)?0:x;}
  function d(v){if(v instanceof Date)return v;var s=t(v),m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})/),x=m?new Date(+m[3],+m[2]-1,+m[1]):new Date(s);return isNaN(x.getTime())?null:x;}
  function prop(k,z){try{return t(PropertiesService.getScriptProperties().getProperty(k)||z);}catch(_){return z;}}
  function rows(name){var id=prop('DB_FIN_ID','');if(!id)throw new Error('DB_FIN_ID nao configurado.');var s=SpreadsheetApp.openById(id).getSheetByName(name);if(!s||s.getLastRow()<2)return[];var v=s.getDataRange().getValues(),h=v.shift().map(t);return v.map(function(r){var o={};h.forEach(function(k,i){o[k]=r[i];});return o;}).filter(function(o){return Object.keys(o).some(function(k){return t(o[k]);});});}
  function cardId(r){return t(r.CARTAO_ID||r.ID);} function prestId(r){return t(r.LANCAMENTO_ID||r.ID);} function extId(r){return t(r.EXTRATO_ID||r.ID);} function final4(r){return t(r.FINAL_CARTAO||r.CARTAO_FINAL||r.NUMERO_FINAL_4).slice(-4);}
  function context(){var cs=rows(A.cartoes),ids={},fins={};cs.forEach(function(c){ids[cardId(c)]=c;fins[final4(c)]=c;});return{cards:cs,ids:ids,fins:fins};}
  function cpfRow(r,c){var x=cpf(r.CPF_COLABORADOR||r.FUNCIONARIO_CPF),card=c.ids[cardId(r)]||c.fins[final4(r)];return x||(card?cpf(card.CPF_COLABORADOR):'');}
  function inventory(){return[{entidade:'COLABORADOR_FLASH',aba:A.cartoes,chave:'CPF_COLABORADOR'},{entidade:'CARTAO_FLASH',aba:A.cartoes,chave:'CARTAO_ID'},{entidade:'RECARGA_FLASH',aba:A.recargas,chave:'RECARGA_ID'},{entidade:'PRESTACAO_FLASH',aba:A.prestacoes,chave:'LANCAMENTO_ID'},{entidade:'EXTRATO_FLASH',aba:A.extratos,chave:'EXTRATO_ID'},{entidade:'DOCUMENTO_FLASH',aba:A.docs,chave:'DOCUMENTO_ID / TERMO_ID'},{entidade:'COBRANCA_FLASH',aba:A.pendencias,chave:'PENDENCIA_ID'}];}
  function pre(){var c=context(),ps=rows(A.prestacoes),used={};var out=rows(A.extratos).map(function(e){var ec=cpfRow(e,c),card=c.ids[cardId(e)]||c.fins[final4(e)];if(!card)return{extratoId:extId(e),classificacao:'CARTAO_NAO_CADASTRADO',score:0};if(!ec)return{extratoId:extId(e),classificacao:'COLABORADOR_NAO_IDENTIFICADO',score:0};var ev=Math.abs(n(e.VALOR)),ed=d(e.DATA_TRANSACAO),best=null;ps.forEach(function(p){if(used[prestId(p)]||cpfRow(p,c)!==ec)return;var pc=c.ids[cardId(p)]||p;if(cardId(p)!==cardId(card)&&final4(pc)!==final4(card))return;var dif=Math.abs(Math.abs(n(p.VALOR))-ev),pd=d(p.DATA_GASTO),dias=pd&&ed?Math.abs(Math.round((pd-ed)/86400000)):99,score=(cardId(p)===cardId(card)?35:25)+20+(dif<.01?30:dif<=5?10:0)+(dias===0?15:dias<=3?8:0);if(!best||score>best.score)best={p:p,dif:dif,score:score};});if(!best||best.score<35)return{extratoId:extId(e),cpf:ec,classificacao:'SEM_PRESTACAO',score:best?best.score:0};var cl=!t(best.p.COMPROVANTE_FILE_ID||best.p.COMPROVANTE_LINK)?'SEM_COMPROVANTE':best.dif>=.01?'DIVERGENCIA_VALOR':best.score>=92?'MATCH_EXATO':'PROVAVEL_MATCH';if(cl==='MATCH_EXATO'||cl==='PROVAVEL_MATCH')used[prestId(best.p)]=1;return{extratoId:extId(e),prestacaoId:prestId(best.p),cpf:ec,cartaoId:cardId(card),classificacao:cl,score:best.score,requerConfirmacaoFinanceiro:true};});var resumo={};out.forEach(function(x){resumo[x.classificacao]=(resumo[x.classificacao]||0)+1;});return{ok:true,semGravar:true,total:out.length,resumo:resumo,sugestoes:out};}
  function col(cp){var x=cpf(cp),cs=context().cards.filter(function(c){return cpf(c.CPF_COLABORADOR)===x;});if(!x||!cs.length)throw new Error('Colaborador/CPF nao encontrado.');return{cpf:x,nome:t(cs[0].FUNCIONARIO_NOME),card:cs[0]};}
  function esc(v){return t(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
  function head(title,c){return'<!doctype html><html><head><meta charset="utf-8"><style>body{font:14px Arial;max-width:820px;margin:32px auto;color:#1f2937}h1{color:#0f2d52}.alerta{background:#fff7ed;border-left:4px solid #f59e0b;padding:12px}.ass{display:flex;gap:60px;margin-top:70px}.ass div{flex:1;border-top:1px solid;text-align:center;padding:8px}</style></head><body><h1>'+esc(title)+'</h1><p><b>Colaborador:</b> '+esc(c.nome)+'<br><b>CPF:</b> '+esc(c.cpf)+'</p>';}
  function termo(cp){var c=col(cp);return head('Termo de Responsabilidade — Cartao Flash',c)+'<p>Os recursos pertencem a empresa e devem ser usados apenas em despesas autorizadas. O colaborador deve prestar contas pelo cartao usado, anexar comprovante legivel e cumprir o prazo de 3 dias, salvo politica vigente.</p><div class="alerta">Pendencia vencida pode bloquear recargas, gerar advertencia e medidas administrativas cabiveis, sempre com revisao humana.</div><div class="ass"><div>Assinatura do colaborador</div><div>Ciencia da empresa</div></div></body></html>';}
  function report(cp,periodo){var c=col(cp),cx=context(),pfx=t(periodo),ps=rows(A.prestacoes).filter(function(p){return cpfRow(p,cx)===c.cpf&&(!pfx||t(p.DATA_GASTO).indexOf(pfx)>=0);});return head('Relatorio Mensal Flash — '+(pfx||'todos os periodos'),c)+'<p>Total de prestacoes: <b>'+ps.length+'</b>. Valor: <b>R$ '+ps.reduce(function(s,p){return s+Math.abs(n(p.VALOR));},0).toFixed(2)+'</b>.</p></body></html>';}
  function charges(){var c=context(),today=new Date();today.setHours(0,0,0,0);var out=rows(A.pendencias).filter(function(p){return['RESOLVIDO','CANCELADO','INATIVO'].indexOf(up(p.STATUS))<0;}).map(function(p){var cp=cpfRow(p,c),card=c.cards.filter(function(x){return cpf(x.CPF_COLABORADOR)===cp;})[0]||{},lim=d(p.DATA_LIMITE_ESCLARECIMENTO),days=lim?Math.max(0,Math.floor((today-lim)/86400000)):0,value=Math.abs(n(p.VALOR_ENVOLVIDO)),name=t(card.FUNCIONARIO_NOME||p.FUNCIONARIO_NOME);return{cpf:cp,colaborador:name,pendenciaId:t(p.PENDENCIA_ID||p.ID),valorPendente:value,diasAtraso:days,canalSugerido:t(card.FUNCIONARIO_EMAIL)?'EMAIL':t(card.FUNCIONARIO_TELEFONE)?'WHATSAPP':'CONTATO_MANUAL',nivelCobranca:days>=15?'ADVERTENCIA':days>=7?'ESCALONADA':days>0?'VENCIDA':'LEMBRETE',mensagemSugerida:'Ola, '+name+'. Ha uma pendencia Flash de R$ '+value.toFixed(2)+'. Regularize a prestacao e o comprovante.',semEnviar:true};});return{ok:true,semEnviar:true,total:out.length,cobrancas:out};}
  function notice(cp,adv){var c=col(cp),list=charges().cobrancas.filter(function(x){return x.cpf===c.cpf;}),value=list.reduce(function(s,x){return s+x.valorPendente;},0);return head(adv?'Advertencia Flash':'Notificacao de Pendencia Flash',c)+'<p>Existem <b>'+list.length+' pendencia(s)</b>, total de <b>R$ '+value.toFixed(2)+'</b>.</p><div class="alerta">Regularize a prestacao e envie comprovante legivel. A avaliacao final e humana.</div></body></html>';}
  function blockAudit(){var m={};charges().cobrancas.forEach(function(x){if(x.diasAtraso>0){if(!m[x.cpf])m[x.cpf]={cpf:x.cpf,colaborador:x.colaborador,pendenciasVencidas:0,valorPendente:0,bloqueioSugerido:true};m[x.cpf].pendenciasVencidas++;m[x.cpf].valorPendente+=x.valorPendente;}});return{ok:true,semGravar:true,regra:'Pendencia vencida bloqueia recarga; desbloqueio manual exige motivo.',colaboradores:Object.keys(m).map(function(k){return m[k];})};}
  function audit(){var c=context(),active=prop('FLASH_OPERACAO_CONTROLADA_ATIVA','false')==='true',general=prop('FLASH_LIBERACAO_GERAL','false')==='true',finGeneral=prop('FIN_LIBERACAO_GERAL','false')==='true',auth=prop('FLASH_CPFS_AUTORIZADOS','').split(',').map(cpf),checks={cpfContaPrincipal:c.cards.some(function(x){return!!cpf(x.CPF_COLABORADOR);}),cartoesVinculados:c.cards.some(function(x){return!!cpf(x.CPF_COLABORADOR)&&!!cardId(x);}),recargaPorCpf:rows(A.recargas).every(function(x){return up(x.STATUS)==='CANCELADA'||!!cpfRow(x,c);}),prestacaoPorCartao:rows(A.prestacoes).every(function(x){return up(x.STATUS)==='INATIVO'||!!cardId(x);}),documentosHtmlDisponiveis:true,conciliacaoInteligenteDisponivel:true,cobrancaPreparada:true,bloqueioPendenciaPreparado:true,operacaoControladaAtiva:active,brunaAutorizada:auth.indexOf(BRUNA)>=0,cpfNaoAutorizadoBloqueado:active&&!general,liberacaoGeralFalse:!general&&!finGeneral,flash44Intacto:c.cards.some(function(x){return t(x.IDENTIFICADOR_CARTAO)==='PILOTO_FLASH44';})},fails=Object.keys(checks).filter(function(k){return checks[k]!==true;});return{ok:fails.length===0,semGravar:true,auditoria:'FLASH.6.0',cpfAutorizadoMantido:BRUNA,checks:checks,falhas:fails,inventarioAbas:inventory(),confirmacoes:{recargaAutomaticaCriada:false,lancamentoAutomaticoCriado:false,emailOuWhatsappEnviado:false,producaoV2Publicada:false}};}
  return{inventory:inventory,pre:pre,termo:termo,report:report,charges:charges,notice:notice,blockAudit:blockAudit,audit:audit};
})();
function PRE_CONCILIAR_FLASH_IA_SEM_GRAVAR(){return FLASH60.pre();}
function GERAR_HTML_TERMO_RESPONSABILIDADE_FLASH_SEM_GRAVAR(cpf){return FLASH60.termo(cpf);}
function GERAR_HTML_RELATORIO_MENSAL_COLABORADOR_FLASH_SEM_GRAVAR(cpf,periodo){return FLASH60.report(cpf,periodo);}
function GERAR_HTML_NOTIFICACAO_PENDENCIA_FLASH_SEM_GRAVAR(cpf){return FLASH60.notice(cpf,false);}
function GERAR_HTML_ADVERTENCIA_FLASH_SEM_GRAVAR(cpf){return FLASH60.notice(cpf,true);}
function PREPARAR_COBRANCAS_FLASH_SEM_ENVIAR(){return FLASH60.charges();}
function AUDITAR_FLASH_BLOQUEIO_RECARGA_POR_PENDENCIA_SEM_GRAVAR(){return FLASH60.blockAudit();}
function AUDITAR_FLASH60_ARQUITETURA_FINAL_SEM_GRAVAR(){return FLASH60.audit();}
function INVENTARIAR_FLASH60_ABAS_SEM_GRAVAR(){return{ok:true,semGravar:true,abas:FLASH60.inventory()};}
